services:
  project_manage:
    image: project_manage:1.1.0
    container_name: project_manage
    ports:
      - "5566:8501"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
    restart: always